language: python  

python:
  - "3.6"

install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions

script:
  - mkdocs build

after_script:
  - cp CNAME site/CNAME
  - cd site
  - git init
  - git config user.name "Travis CI"
  - git config user.email "Jerry.x@outlook.com"
  - git add .
  - git commit -m "update by Travis-CI"
  - git push "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:master

env:
    global:
        - GH_REF: github.com/TwoDragonLake/tdl-saas-archive.git