sudo: false
language: python  
dist: trusty
git:
  depth: false
  
python:
  - "3.6"
install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions
script:
  - mkdocs build --clean
  - ls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GH_TOKEN}  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
