sudo: false
language: python  
dist: trusty
git:
  depth: false
  
python:
  - "3.7.2"
install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions
script:
  - mkdocs build --clean
  - ls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 126b35f3692b9ba9f4afb5c95fc6db3860163ed3  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master